module.exports = {
  content: ["./public/**/*.html", "./public/**/*.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#00c853",
        "secondary": "#00c853",
        "surface-dim": "#101419",
        "inverse-surface": "#e0e2ea",
        "tertiary": "#ffb871",
        "on-primary-container": "#004060",
        "surface-tint": "#00b0ff",
        "primary-fixed-dim": "#00b0ff",
        "on-surface": "#e0e2ea",
        "error-container": "#93000a",
        "outline": "#88929c",
        "primary-fixed": "#cae6ff",
        "secondary-fixed-dim": "#00c853",
        "on-primary-fixed": "#001e30",
        "on-tertiary-container": "#5a3200",
        "tertiary-fixed-dim": "#ffb871",
        "on-secondary-fixed": "#002108",
        "on-secondary-container": "#002108",
        "surface-container-highest": "#31353b",
        "surface-container-lowest": "#0a0e13",
        "on-error-container": "#ffdad6",
        "surface": "#101419",
        "on-primary": "#00344f",
        "on-secondary-fixed-variant": "#00531e",
        "on-background": "#e0e2ea",
        "on-tertiary-fixed": "#2d1600",
        "error": "#ffb4ab",
        "surface-container-high": "#262a30",
        "secondary-fixed": "#00c853",
        "surface-container-low": "#181c21",
        "on-primary-fixed-variant": "#004b70",
        "primary-container": "#00b0ff",
        "inverse-primary": "#006493",
        "outline-variant": "#3e4851",
        "on-tertiary": "#4a2800",
        "surface-bright": "#36393f",
        "on-tertiary-fixed-variant": "#6a3c00",
        "surface-variant": "#31353b",
        "on-surface-variant": "#bdc8d3",
        "tertiary-container": "#f08f0a",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#2d3136",
        "background": "#0B0F14",
        "surface-container": "#1c2025",
        "primary": "#00b0ff",
        "on-error": "#690005",
        "tertiary-fixed": "#ffdcbe"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "16px",
        "md": "16px",
        "xl": "40px",
        "base": "4px",
        "xs": "4px",
        "lg": "24px",
        "margin-desktop": "24px",
        "gutter": "12px",
        "sm": "8px",
        "panel-padding": "12px",
        "container-margin": "16px"
      },
      fontFamily: {
        "data-mono": ["JetBrains Mono"],
        "headline-md-mobile": ["Geist"],
        "body-lg": ["Geist"],
        "body-md": ["Geist"],
        "headline-md": ["Geist"],
        "display-lg": ["Geist"],
        "label-sm": ["JetBrains Mono"],
        "label-xs": ["Inter"],
        "body-base": ["Inter"]
      },
      fontSize: {
        "data-mono": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "headline-md-mobile": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "display-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["11px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "label-xs": ["11px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "body-base": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
